; screen resolution
width=1920
height=1080

; adapter 0xf805 is "NVIDIA GeForce RTX 4050 Laptop GPU", VidMem=5921 MB, SysMem=0 MB, SharedMem=8003 MB, VendorId=0x10DE, DeviceId=0x28A1, SubSysId=0x32281043, Revision=0xA1
; adapter 0xf502 is "Intel(R) UHD Graphics", VidMem=128 MB, SysMem=0 MB, SharedMem=8003 MB, VendorId=0x8086, DeviceId=0x4626, SubSysId=0x32281043, Revision=0xC
; adapter 0xf7ac is "Microsoft Basic Render Driver", VidMem=0 MB, SysMem=0 MB, SharedMem=8003 MB, VendorId=0x1414, DeviceId=0x8C, SubSysId=0x0, Revision=0x0
adapter=0xf805 ; the adapter id should be one listed above!
monitor=0 ; monitor output (0 = default, 1 = secondary etc)

; graphics quality
characters=3 ; face texture quality 0=low 1=medium 2=high 3=highest
frontendcharacters=1 ; face texture quality 0=low 1=medium 2=high 3=highest
vsync=1 ; vertical sync 0=off 1=on
anisotropy=0 ; anisotropic texture filtering level 0=off 16=max
mipBias=-0.5 ; mip map level bias
gbufferScale=1.0 ; gbuffer scale
fullscreen=1 ; fullscreen mode 0=off 1=on
dof=1 ; depth of field quality 0=off 1=on
bloom=2 ; bloom quality 0=off 1=gaussian(faster) 2=hexagonal(higher quality)
light_flares=2 ; light flare quality 0=off 1=via bloom 2=high quality
brightness=0.56 ; gamma / screen brightness (darkest: 0, brightest: 1)
crowd=1 ; crowd texture quality (size) 0=off, 1=reduced, 2=high, 3=ultra
grass=1 ; grass quality 0=2d 1=3d
shadows=2 ; 0=off 1=lowest quality 2=high quality, 3=medium quality, 4=low quality
lighting=1 ; lighting quality 0=low 1=high
ao=0 ; ambient occlusion 0=off 1=sometimes(cinematics only) 2=on
resolutionscaling=0 ; dynamic resolution 0=off 1=on
antialiasing=1 ; antialiasing 0=off 1=fxaa 2=taa
autoletterboxing=1 ; autoletterboxing 0=off 1=on
shadow_smoothing=0 ; depth-aware screen space smoothing of shadows, 0=off 1=on
shadow_contactHardening=0 ; contact hardening soft shadows, 0=off 1=on
preset=3
